query($addr: String!, $exchange: String!) {
  transactions(
    owners: [$addr]
    recipients: [$exchange]
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Genesis" }
    ]
    first: 1
  ) {
    edges {
      node {
        id
      }
    }
  }
}
