query($recipients: [String!], $min: Int, $num: Int) {
  transactions(
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: ["Buy", "Sell"] }
    ]
    block: { min: $min }
    first: $num
  ) {
    edges {
      node {
        id
        block {
          height
          timestamp
        }
      }
    }
  }
}
