query($owners: [String!], $recipients: [String!], $num: Int) {
  transactions(
    owners: $owners
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Trade-Opcode", values: ["Buy", "Sell"] }
    ]
    first: $num
  ) {
    edges {
      node {
        id
      }
    }
  }
}
