query ($recipients: [String!], $min: Int, $num: Int) {
  transactions(
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: ["Buy", "Sell", "Cancel", "Swap"] }
    ]
    block: { min: $min }
    first: $num
  ) {
    edges {
      node {
        id
        block {
          height
          timestamp
        }
        owner {
          address
        }
        quantity {
          ar
        }
        tags {
          name
          value
        }
      }
    }
  }
}
